/* Nearest Forest — map view.

   A canvas map that works with no signal. The coastline is bundled
   (app/data/boundary.json, generated by scripts/build_boundary.py) rather than
   fetched as tiles, because the whole app exists for places with no data. The
   optional tile layer decided on board card 0007 lands on top of this later
   (card 0009); everything here must keep working with tiles absent, so the
   outline is never treated as a placeholder.

   Pure maths lives in core.js (window.NF) so scripts/selftest.js covers it.
   This file is the canvas, the gestures and the DOM, and nothing else. */
'use strict';

var NFMap = (function () {
  var boundary = null;          // decoded rings, world coords
  var loadError = null;
  var hooks = null;
  var canvas, ctx, wrap;
  var W = 0, H = 0, DPR = 1;

  var view = { cx: 0.5, cy: 0.5, scale: 1 };
  var minScale = 1, maxScale = 1;
  var markers = [];             // { x, y, site } in screen px, rebuilt each draw
  var open = false;

  /* Pointer bookkeeping for pan and pinch. */
  var pointers = {};
  var nPointers = 0;
  var dragged = 0;
  var pinchStart = null;
  var lastTap = 0;

  /* ---------- theme ---------- */
  /* Read from the stylesheet rather than duplicated here, so the map follows
     the same dark/light switch as everything else and cannot drift from it. */
  function themeColours() {
    var cs = getComputedStyle(document.documentElement);
    var v = function (n, fallback) {
      var got = cs.getPropertyValue(n);
      return (got && got.trim()) || fallback;
    };
    return {
      sea: v('--bg', '#0f1a12'),
      land: v('--bg2', '#16241a'),
      coast: v('--line', '#26382b'),
      ink: v('--fg', '#eaf3ec'),
      dim: v('--dim', '#9db3a4'),
      accent: v('--accent', '#6fd08c'),
      accentInk: v('--accent-ink', '#06210f')
    };
  }

  /* ---------- boundary ---------- */
  function decodeRing(flat) {
    /* Delta-encoded integers at 1e-4 degrees; see scripts/build_boundary.py. */
    var pts = [], x = 0, y = 0, i;
    for (i = 0; i < flat.length; i += 2) {
      x += flat[i]; y += flat[i + 1];
      pts.push([NF.projX(x / 10000), NF.projY(y / 10000)]);
    }
    return pts;
  }

  function loadBoundary() {
    if (boundary || loadError) return Promise.resolve();
    return fetch('data/boundary.json').then(function (r) {
      if (!r.ok) throw new Error('HTTP ' + r.status);
      return r.json();
    }).then(function (d) {
      boundary = {
        bbox: d.bbox,
        parts: d.parts.map(function (p) {
          return { name: p.name, rings: p.rings.map(decodeRing) };
        })
      };
    }).catch(function (err) {
      /* The map is the only thing that breaks, so say so here rather than
         taking the list down with it. */
      loadError = err.message;
    });
  }

  /* ---------- view maths ---------- */
  function sizeCanvas() {
    DPR = Math.min(3, window.devicePixelRatio || 1);
    var r = wrap.getBoundingClientRect();
    W = Math.max(1, Math.round(r.width));
    H = Math.max(1, Math.round(r.height));
    canvas.width = Math.round(W * DPR);
    canvas.height = Math.round(H * DPR);
    canvas.style.width = W + 'px';
    canvas.style.height = H + 'px';
    ctx = canvas.getContext('2d');
    ctx.setTransform(DPR, 0, 0, DPR, 0, 0);
  }

  function sx(wx) { return (wx - view.cx) * view.scale + W / 2; }
  function sy(wy) { return (wy - view.cy) * view.scale + H / 2; }

  function clampView() {
    view.scale = Math.max(minScale, Math.min(maxScale, view.scale));
    /* Keep the country from being dragged off-screen entirely: the centre may
       leave the bbox, but never by more than half a viewport, so there is
       always something to grab and a way back. */
    if (!boundary) return;
    var b = boundary.bbox;
    var x0 = NF.projX(b[0]), x1 = NF.projX(b[2]);
    var y0 = NF.projY(b[3]), y1 = NF.projY(b[1]);
    var mx = (W / 2) / view.scale, my = (H / 2) / view.scale;
    view.cx = Math.max(x0 - mx * 0.5, Math.min(x1 + mx * 0.5, view.cx));
    view.cy = Math.max(y0 - my * 0.5, Math.min(y1 + my * 0.5, view.cy));
  }

  function computeScaleLimits() {
    if (!boundary) return;
    var f = NF.fitBounds(boundary.bbox, W, H, 12);
    minScale = f.scale;
    /* 64x is enough to separate two car parks in the same forest without
       letting the outline dissolve into a meaningless wall of coastline. */
    maxScale = f.scale * 64;
  }

  function fitAll() {
    if (!boundary) return;
    var f = NF.fitBounds(boundary.bbox, W, H, 12);
    view.cx = f.cx; view.cy = f.cy; view.scale = f.scale;
  }

  /* Open on something useful: you and the sites you might actually drive to,
     rather than the whole of Great Britain with your dot lost in it. */
  function fitToInterest() {
    var pos = hooks.getPos();
    var sites = hooks.getSites();
    if (!pos || !sites.length) { fitAll(); return; }
    var near = sites.slice(0, 6);
    var lats = [pos.lat], lngs = [pos.lng];
    near.forEach(function (s) { lats.push(s.lat); lngs.push(s.lng); });
    var pad = 0.15;
    var bbox = [Math.min.apply(null, lngs) - pad, Math.min.apply(null, lats) - pad,
                Math.max.apply(null, lngs) + pad, Math.max.apply(null, lats) + pad];
    var f = NF.fitBounds(bbox, W, H, 24);
    view.cx = f.cx; view.cy = f.cy;
    view.scale = Math.min(maxScale, f.scale);
    clampView();
  }

  /* ---------- drawing ---------- */
  function draw() {
    if (!ctx) return;
    var c = themeColours();

    ctx.setTransform(DPR, 0, 0, DPR, 0, 0);
    ctx.fillStyle = c.sea;
    ctx.fillRect(0, 0, W, H);

    if (loadError) {
      ctx.fillStyle = c.ink;
      ctx.font = '15px -apple-system, system-ui, sans-serif';
      ctx.textAlign = 'center';
      ctx.fillText('Map outline unavailable (' + loadError + ').', W / 2, H / 2 - 10);
      ctx.fillStyle = c.dim;
      ctx.fillText('The list still works.', W / 2, H / 2 + 14);
      return;
    }
    if (!boundary) return;

    /* Land. One path for all rings so the fill is a single operation. */
    ctx.beginPath();
    boundary.parts.forEach(function (part) {
      part.rings.forEach(function (ring) {
        var i;
        for (i = 0; i < ring.length; i++) {
          var x = sx(ring[i][0]), y = sy(ring[i][1]);
          if (i === 0) ctx.moveTo(x, y); else ctx.lineTo(x, y);
        }
        ctx.closePath();
      });
    });
    ctx.fillStyle = c.land;
    ctx.fill();
    ctx.strokeStyle = c.coast;
    ctx.lineWidth = 1;
    ctx.stroke();

    /* Markers. Rebuilt every frame because the hit test must agree with what
       is on screen; a cached list is how a tap starts landing on the wrong
       forest after a pan. */
    markers = [];
    var sites = hooks.getSites();
    var zoomed = view.scale > minScale * 5;
    var r = zoomed ? 5 : 3.5;

    sites.forEach(function (s) {
      var x = sx(NF.projX(s.lng)), y = sy(NF.projY(s.lat));
      if (x < -20 || y < -20 || x > W + 20 || y > H + 20) return;
      markers.push({ x: x, y: y, site: s });
    });

    ctx.fillStyle = c.accent;
    markers.forEach(function (m) {
      ctx.beginPath();
      ctx.arc(m.x, m.y, r, 0, Math.PI * 2);
      ctx.fill();
    });

    /* Nearest gets a ring, matching the "Nearest" badge in the list. */
    var nearest = sites[0];
    if (nearest && hooks.getPos()) {
      var nx = sx(NF.projX(nearest.lng)), ny = sy(NF.projY(nearest.lat));
      ctx.beginPath();
      ctx.arc(nx, ny, r + 4, 0, Math.PI * 2);
      ctx.strokeStyle = c.accent;
      ctx.lineWidth = 2;
      ctx.stroke();
    }

    /* Labels only once there is room for them to mean anything. */
    if (zoomed) {
      ctx.font = '600 12px -apple-system, system-ui, sans-serif';
      ctx.textAlign = 'center';
      ctx.textBaseline = 'bottom';
      /* markers is in ranked order, so slicing takes the nearest. Capped low
         on purpose: a stubbed-canvas run drew 32 labels at the default zoom,
         which is a wall of text rather than a legible map. */
      var labelled = markers.slice(0, 12);
      labelled.forEach(function (m) {
        var t = m.site.name;
        if (t.length > 22) t = t.slice(0, 21) + '…';
        ctx.lineWidth = 3;
        ctx.strokeStyle = c.sea;
        ctx.strokeText(t, m.x, m.y - r - 3);      /* halo, so it reads over land */
        ctx.fillStyle = c.ink;
        ctx.fillText(t, m.x, m.y - r - 3);
      });
      ctx.textBaseline = 'alphabetic';
      ctx.textAlign = 'left';
    }

    /* You. Drawn last so nothing can hide it. */
    var pos = hooks.getPos();
    if (pos) {
      var px = sx(NF.projX(pos.lng)), py = sy(NF.projY(pos.lat));
      ctx.beginPath();
      ctx.arc(px, py, 7, 0, Math.PI * 2);
      ctx.fillStyle = c.accentInk;
      ctx.fill();
      ctx.lineWidth = 3;
      ctx.strokeStyle = c.ink;
      ctx.stroke();
      if (pos.stale) {
        ctx.setLineDash([3, 3]);
        ctx.beginPath();
        ctx.arc(px, py, 13, 0, Math.PI * 2);
        ctx.strokeStyle = c.dim;
        ctx.lineWidth = 1.5;
        ctx.stroke();
        ctx.setLineDash([]);
      }
    }
  }

  var raf = 0;
  function schedule() {
    if (raf) return;
    raf = requestAnimationFrame(function () { raf = 0; draw(); });
  }

  /* ---------- gestures ---------- */
  function zoomAbout(factor, px, py) {
    var before = view.scale;
    view.scale = Math.max(minScale, Math.min(maxScale, view.scale * factor));
    var k = view.scale / before;
    if (k === 1) return;
    /* Keep the world point under the finger under the finger. */
    view.cx += (px - W / 2) * (1 / before - 1 / view.scale);
    view.cy += (py - H / 2) * (1 / before - 1 / view.scale);
    clampView();
    schedule();
  }

  function localXY(e) {
    var r = canvas.getBoundingClientRect();
    return { x: e.clientX - r.left, y: e.clientY - r.top };
  }

  function onDown(e) {
    canvas.setPointerCapture(e.pointerId);
    pointers[e.pointerId] = localXY(e);
    nPointers++;
    dragged = 0;
    if (nPointers === 2) {
      var ids = Object.keys(pointers);
      var a = pointers[ids[0]], b = pointers[ids[1]];
      pinchStart = { d: Math.hypot(a.x - b.x, a.y - b.y), scale: view.scale };
    }
  }

  function onMove(e) {
    var p = pointers[e.pointerId];
    if (!p) return;
    var now = localXY(e);

    if (nPointers === 1) {
      var dx = now.x - p.x, dy = now.y - p.y;
      dragged += Math.abs(dx) + Math.abs(dy);
      view.cx -= dx / view.scale;
      view.cy -= dy / view.scale;
      clampView();
      schedule();
    } else if (nPointers === 2 && pinchStart) {
      pointers[e.pointerId] = now;
      var ids = Object.keys(pointers);
      var a = pointers[ids[0]], b = pointers[ids[1]];
      var d = Math.hypot(a.x - b.x, a.y - b.y);
      if (pinchStart.d > 0) {
        dragged += 10;                       /* a pinch is never a tap */
        var target = pinchStart.scale * (d / pinchStart.d);
        var mid = { x: (a.x + b.x) / 2, y: (a.y + b.y) / 2 };
        zoomAbout(target / view.scale, mid.x, mid.y);
      }
      return;
    }
    pointers[e.pointerId] = now;
  }

  function onUp(e) {
    var p = pointers[e.pointerId];
    delete pointers[e.pointerId];
    nPointers = Math.max(0, nPointers - 1);
    if (nPointers < 2) pinchStart = null;
    if (!p || dragged > 8) return;

    var xy = localXY(e);
    var now = Date.now();
    if (now - lastTap < 300) {               /* double tap zooms in */
      lastTap = 0;
      zoomAbout(2, xy.x, xy.y);
      return;
    }
    lastTap = now;

    var hit = NF.pickNearest(markers, xy.x, xy.y, 22);
    if (hit) { lastTap = 0; hooks.onPick(hit.site); }
  }

  /* ---------- public ---------- */
  function init(h) {
    hooks = h;
    wrap = document.getElementById('map');
    canvas = document.getElementById('map-canvas');

    canvas.addEventListener('pointerdown', onDown);
    canvas.addEventListener('pointermove', onMove);
    canvas.addEventListener('pointerup', onUp);
    canvas.addEventListener('pointercancel', function (e) {
      delete pointers[e.pointerId];
      nPointers = Math.max(0, nPointers - 1);
      pinchStart = null;
    });
    canvas.addEventListener('wheel', function (e) {
      e.preventDefault();
      var xy = localXY(e);
      zoomAbout(e.deltaY < 0 ? 1.15 : 1 / 1.15, xy.x, xy.y);
    }, { passive: false });

    document.getElementById('map-fit').addEventListener('click', function () {
      fitToInterest(); schedule();
    });
    document.getElementById('map-all').addEventListener('click', function () {
      fitAll(); schedule();
    });

    window.addEventListener('resize', function () {
      if (!open) return;
      sizeCanvas(); computeScaleLimits(); clampView(); schedule();
    });
  }

  function show() {
    open = true;
    wrap.hidden = false;
    document.body.classList.add('is-mapping');
    loadBoundary().then(function () {
      sizeCanvas();
      computeScaleLimits();
      fitToInterest();
      draw();
    });
  }

  function hide() {
    open = false;
    wrap.hidden = true;
    document.body.classList.remove('is-mapping');
  }

  return {
    init: init,
    show: show,
    hide: hide,
    isOpen: function () { return open; },
    refresh: function () { if (open) schedule(); }
  };
}());
