/* Nearest Forest service worker.

   Precaches the whole app including the dataset, so the app works with no signal.
   Bump CACHE when the app or the data changes: the old cache is then deleted on activate,
   which is the only reliable way to retire a stale dataset on iOS. */
'use strict';

var CACHE = 'nearest-forest-v9-2026-08-10';
var ASSETS = [
  './',
  './index.html',
  './app.css',
  './core.js',
  './map.js',
  './app.js',
  './manifest.webmanifest',
  './data/sites.json',
  './data/boundary.json',
  './icons/icon-180.png',
  './icons/icon-192.png',
  './icons/icon-512.png'
];

self.addEventListener('install', function (e) {
  e.waitUntil(
    Promise.all(ASSETS.map(function (url) {
      // cache:'reload' bypasses the browser's HTTP cache. Without it, a plain
      // addAll() happily fills a brand-new cache with whatever the browser
      // already had: a phone that loaded the old app inside max-age installs
      // the NEW cache name over the OLD bytes and is then stale forever.
      // Bumping CACHE does not rescue it, because the next bump does the same.
      // This cost one "renders on desktop, not on phone" bug on 2026-08-08.
      return fetch(new Request(url, { cache: 'reload' })).then(function (res) {
        if (!res || !res.ok) {
          throw new Error('precache failed: ' + url + ' -> ' + (res && res.status));
        }
        return { url: url, res: res };
      });
    })).then(function (all) {
      // Write only once every asset has arrived, keeping addAll's atomicity: a
      // half-populated cache looks fine until you are somewhere with no signal.
      return caches.open(CACHE).then(function (c) {
        return Promise.all(all.map(function (a) { return c.put(a.url, a.res); }));
      });
    }).then(function () {
      return self.skipWaiting();
    })
  );
});

self.addEventListener('activate', function (e) {
  e.waitUntil(
    caches.keys().then(function (keys) {
      return Promise.all(keys.map(function (k) {
        return k === CACHE ? null : caches.delete(k);
      }));
    }).then(function () {
      return self.clients.claim();
    })
  );
});

/* Cache-first over the precached shell, and nothing else is ever written here.
   The dataset is a static snapshot regenerated by the build, so there is nothing to
   revalidate at runtime and a network round trip would only add latency in exactly the
   low-signal places this app is used.

   This handler used to cache every same-origin GET it saw. `api/tiles.php` is
   same-origin, so every map tile Rob panned over was written into this cache: 300
   tiles measured at 6MB, unbounded. On iOS a Cache Storage that outgrows its quota is
   evicted wholesale, which takes the app's own offline copy with it -- the app then
   works online and is dead in a car park, which is the one thing it exists to avoid.
   The cache now holds exactly ASSETS and nothing more. */
self.addEventListener('fetch', function (e) {
  var req = e.request;
  if (req.method !== 'GET') return;
  var url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  // api/ is the tile proxy and the Shortcut endpoint. Neither belongs in the offline
  // cache: tiles are unbounded and optional by decision, and the endpoint is for the
  // Shortcut, not the PWA. Tiles already carry a 7-day max-age, so the browser's own
  // HTTP cache keeps recently-seen ones available offline. That is the right layer for
  // something that is allowed to be missing.
  if (url.pathname.indexOf('/api/') !== -1) return;

  e.respondWith(
    // Scoped to CACHE on purpose: an unscoped caches.match() searches every cache in
    // creation order, so mid-update the outgoing version can answer for the incoming one.
    caches.match(req, { cacheName: CACHE }).then(function (hit) {
      if (hit) return hit;
      return fetch(req).catch(function () {
        // Navigations must still resolve offline, or the app shows a Safari error page.
        if (req.mode === 'navigate') return caches.match('./index.html', { cacheName: CACHE });
        throw new Error('offline and not cached: ' + req.url);
      });
    })
  );
});
