/* Nearest Forest service worker.

   Precaches the whole app including the dataset, so the app works with no signal.
   Bump CACHE when the app or the data changes: the old cache is then deleted on activate,
   which is the only reliable way to retire a stale dataset on iOS. */
'use strict';

var CACHE = 'nearest-forest-v6-2026-08-08';
var ASSETS = [
  './',
  './index.html',
  './app.css',
  './core.js',
  './map.js',
  './app.js',
  './manifest.webmanifest',
  './data/sites.json',
  './data/boundary.json',
  './icons/icon-180.png',
  './icons/icon-192.png',
  './icons/icon-512.png'
];

self.addEventListener('install', function (e) {
  e.waitUntil(
    Promise.all(ASSETS.map(function (url) {
      // cache:'reload' bypasses the browser's HTTP cache. Without it, a plain
      // addAll() happily fills a brand-new cache with whatever the browser
      // already had: a phone that loaded the old app inside max-age installs
      // the NEW cache name over the OLD bytes and is then stale forever.
      // Bumping CACHE does not rescue it, because the next bump does the same.
      // This cost one "renders on desktop, not on phone" bug on 2026-08-08.
      return fetch(new Request(url, { cache: 'reload' })).then(function (res) {
        if (!res || !res.ok) {
          throw new Error('precache failed: ' + url + ' -> ' + (res && res.status));
        }
        return { url: url, res: res };
      });
    })).then(function (all) {
      // Write only once every asset has arrived, keeping addAll's atomicity: a
      // half-populated cache looks fine until you are somewhere with no signal.
      return caches.open(CACHE).then(function (c) {
        return Promise.all(all.map(function (a) { return c.put(a.url, a.res); }));
      });
    }).then(function () {
      return self.skipWaiting();
    })
  );
});

self.addEventListener('activate', function (e) {
  e.waitUntil(
    caches.keys().then(function (keys) {
      return Promise.all(keys.map(function (k) {
        return k === CACHE ? null : caches.delete(k);
      }));
    }).then(function () {
      return self.clients.claim();
    })
  );
});

/* Cache-first. The dataset is a static snapshot regenerated by the build, so there is
   nothing to revalidate at runtime and a network round trip would only add latency in
   exactly the low-signal places this app is used. */
self.addEventListener('fetch', function (e) {
  var req = e.request;
  if (req.method !== 'GET') return;
  if (new URL(req.url).origin !== self.location.origin) return;

  e.respondWith(
    caches.match(req).then(function (hit) {
      if (hit) return hit;
      return fetch(req).then(function (res) {
        if (res && res.ok) {
          var copy = res.clone();
          caches.open(CACHE).then(function (c) { c.put(req, copy); });
        }
        return res;
      }).catch(function () {
        // Navigations must still resolve offline, or the app shows a Safari error page.
        if (req.mode === 'navigate') return caches.match('./index.html');
        throw new Error('offline and not cached: ' + req.url);
      });
    })
  );
});
